name: Get new udemy cookie every day

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # At 16:00 every day

env:
  # Setting an environment variable with the value of a configuration variable
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
        id: setup-chrome
      - run: |
          echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
          ${{ steps.setup-chrome.outputs.chrome-path }} --version

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          cache: 'pip'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: |
          python main.py

      - name: commit new log changes
        run: |
          git config --global user.email "minhkhuong2404@users.noreply.github.com"
          git config --global user.name "Lữ Minh Khương"
          git add .
          git commit -m "Update cookie file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}